### PR TITLE
Release `cardano-slotting` and `cardano-binary`

### PR DESCRIPTION
**Pull request by jasagredo**

### CODE REVIEW

**Review by lehins — APPROVED** [review]
:+1:

**Review by lehins — CHANGES_REQUESTED** [review]
Dammit, I just realized there is a mistake

**Comment by jasagredo** [comment]
Waiting on input-output-hk/cardano-base#448

**Review by lehins — APPROVED** [review]
:+1: Looks good now :slightly_smiling_face:

**Pull request merged**
