### PR TITLE
Release the ledger packages from the release branches for the 1.35 node release

### PR DESCRIPTION
**Pull request by michaelpj**
Do not merge this until I've tested that it works.

### CODE REVIEW

**Comment by JaredCorduan** [comment]
The versions here would line up better with the ledger release branch if they used `1.1.0.0` instead of `0.1.1.0`.

**Comment by michaelpj** [comment]
Discussed the version issue with Jared, I think this is okay for now. I'm pretty sure what I'm releasing is not wrong, so I'm going to merge it and see if I need more later.

**Comment by michaelpj** [comment]
Turns out this was completely wrong.

**Comment by andreabedini** [comment]
Commit 4c520df005ef63f54acd478fbe837fc8dd35b366 has been removed from the commit history.

**Pull request merged**
