### PR TITLE
coot/io sim 0.6.0.0

### PR DESCRIPTION
**Pull request by coot**
- Added io-classes-0.6.0.0
- Added io-sim-0.6.0.0
- Added strict-stm-0.6.0.0
- Disable io-sim-0.5
- Added strict-mvar-0.1.0.0

### CODE REVIEW

**Comment by coot** [comment]
This PR needs to be updated after input-output-hk/io-sim#81.

**Comment by michaelpj** [comment]
`strict-stm` and `strict-mvar` are not in CODEOWNERS currently, please add them

**Comment by coot** [comment]
Thanks, some other our packages where also missing.

**Comment by michaelpj** [comment]
I'm not totally sure what's going on here, can you try approving the PR yourself and see if that works?

**Comment by coot** [comment]
I cannot, I can only leave a comment.

**Review by bolt12 — APPROVED** [review]

**Comment by coot** [comment]
It seems @bolt12 approval wasn't enough.

**Comment by coot** [comment]
The message sais:

> input-output-hk/cardano-haskell-packages-trustees was requested for review as a code owner 

I am in that group, but I cannot auto review the PR.

**Comment by michaelpj** [comment]
How annoying. I guess I'm just going to turn off the code owner required review, too annoying.

**Review by michaelpj — APPROVED** [review]

**Comment by coot** [comment]
That's likely the last `CHaP` release of `io-sim` & friends.

**Pull request merged**
