### PR TITLE
Let hydra build all packages

### PR DESCRIPTION
**Pull request by andreabedini**

### CODE REVIEW

**Comment by michaelpj** [comment]
Still seems to be doing nothing :thinking:

**Comment by andreabedini** [comment]
```
...
skipping job with illegal name '1.0.0.0'
skipping job with illegal name '0.1.0.0'
skipping job with illegal name '0.1.1.1'
skipping job with illegal name '0.1.1.2'
skipping job with illegal name '1.0.0.0'
skipping job with illegal name '1.0.0.0'
skipping job with illegal name '0.1.0.0'
skipping job with illegal name '0.1.1.1'
skipping job with illegal name '0.1.1.2'
skipping job with illegal name '1.0.0.0'
skipping job with illegal name '1.3.0'
...
```

now I remember why I using `0_1_1_2` :-( So annoying!

**Comment by andreabedini** [comment]
> You can use dots, quoted iirc. But that UX in nix is really annoying.

You can in the nix language but hydra-eval-jobset will reject them anyway.

**Comment by andreabedini** [comment]
This has bitrotten a bit but the main branch moved into the same direction. I'll close this for the moment.

**Pull request closed without merging**
