### PR TITLE
Clean up version flags in add-from-github

### PR DESCRIPTION
**Pull request by michaelpj**
- The flag to force the version was appealingly named `-v` and looked like you were just supposed to always pass the version. I made it scary and changed the flag so that anyone who is currently using it gets tripped up
- The "revision" flag is extremely confusing given we also have, you know, revisions. It's also not used that much, so I just removed it.

### CODE REVIEW

**Comment by angerman** [comment]
This seems sensible.

**Comment by angerman** [comment]
This makes me wonder if we want to have a GitHub action that shellchecks our shell scripts?

**Comment by michaelpj** [comment]
By all means...

**Comment by michaelpj** [comment]
Also personally I would prefer it if we made foliage sub-commands for these operations...

**Comment by angerman** [comment]
> Also personally I would prefer it if we made foliage sub-commands for these operations...

@michaelpj you mean all the shell scripts to be turned into `foliage cmd ...`?

**Comment by michaelpj** [comment]
Yes exactly. Foliage knows how to do all this stuff correctly already.

**Pull request merged**
