### PR TITLE
Release plutus-1.10.0.0

### PR DESCRIPTION
**Pull request by effectfully**

### CODE REVIEW

**Comment by bezirg** [comment]
I think it's better to have a git commit hash in the rev field

**Comment by michaelpj** [comment]
Yeah, we've generally been using a hash. It's less obviously correct... but tags are technically mutable. It's not clear what the best policy is, but so far we've mostly been using hashes.

**Comment by effectfully** [comment]
Makes sense, I'll fix it.

**Comment by bezirg** [comment]
@effectfully Isn't this the hash? https://github.com/input-output-hk/plutus/commit/24399d7c134f981ef00b74bbfe905b7980583e24

**Comment by effectfully** [comment]
> Maybe you took the hash of the PR?

Nope:

```
[plutus-shell]$ git tag -d 1.10.0.0
Deleted tag '1.10.0.0' (was 53ffd7f67)
[plutus-shell]$ git fetch --tags
<...>
[plutus-shell]$ git rev-parse 1.10.0.0
53ffd7f67b904822eac2857985499491c545b049
```

`git show 53ffd7f67b904822eac2857985499491c545b049` starts like this:

```
tag 1.10.0.0
Tagger: effectfully <effectfully@gmail.com>
Date:   Tue Aug 8 17:11:53 2023 +0200

1.10.0.0

commit 24399d7c134f981ef00b74bbfe905b7980583e24 (tag: 1.10.0.0)
Author: effectfully <effectfully@gmail.com>
Date:   Thu Aug 3 11:28:35 2023 +0200

    [Release] 1.10.0.0 (#5452)

diff --git a/doc/read-the-docs-site/plutus-doc.cabal b/doc/read-the-docs-site/plutus-doc.cabal
index 916f0652b..50a06fc29 100644
--- a/doc/read-the-docs-site/plutus-doc.cabal
+++ b/doc/read-the-docs-site/plutus-doc.cabal
@@ -77,9 +77,9 @@ executable doc-doctests
     , containers
     , flat               ^>=0.6
     , lens
-    , plutus-core        ^>=1.9
-    , plutus-ledger-api  ^>=1.9
-    , plutus-tx          ^>=1.9
+    , plutus-core        ^>=1.10
+    , plutus-ledger-api  ^>=1.10
+    , plutus-tx          ^>=1.10
```

You can see that it includes the commit you reference. I suppose `git tag` creates its own hash.

Are you sure we should include the hash of the commit rather than the hash of the tag? I'll change it then.

**Comment by zliu41** [comment]
@effectfully Based on [this](https://stackoverflow.com/questions/66913267/wrong-commit-hash-with-git-rev-parse-tag), the hash should be the one @bezirg said.

```
$ git rev-parse 1.10.0.0^{commit}
24399d7c134f981ef00b74bbfe905b7980583e24
```

**Comment by zliu41** [comment]
Actually perhaps either one is fine. But commit hash should definitely work.

**Comment by effectfully** [comment]
> But commit hash should definitely work.

OK, perfect, changed it to the commit hash and enabled auto-merge.

**Review by bezirg — APPROVED** [review]

**Comment by michaelpj** [comment]
Sorry, something else got merged, so you need to rebase and fix the timestamps, see the README

**Pull request merged**
