### PR TITLE
Update `ouroboros-consensus-cardano`

### PR DESCRIPTION
**Pull request by Jasagredo**
For some reason my rebase of the branch I just merged missed this file.

### CODE REVIEW

**Review by jorisdral — APPROVED** [review]

**Comment by michaelpj** [comment]
This is a problem: you want to mutate a package that you released. We don't currently let you do that easily. Probably we should just let it slide in this instance, WDYT @andreabedini

**Comment by Jasagredo** [comment]
I'm releasing `ouroboros-consensus-cardano` at version `0.3.0.0` instead. Will update this PR once bors merges the one in ouroboros-network https://github.com/input-output-hk/ouroboros-network/pull/4360 Sorry for the noise

**Comment by Jasagredo** [comment]
It was my fault as I was not aware that `ouroboros-consensus-cardano` was already released at version `0.2.0.0` and I didn't notice it while pushing my previous PR

**Comment by michaelpj** [comment]
Hmm, I wonder if there's a tooling issue. Did you use `add-from-github` and try to add a version that already existed and it didn't give you a scary error or something?

**Comment by Jasagredo** [comment]
No, I did it manually :sweat_smile: . As I was re-reading the README I found out that script existed and I just used it now for this new release

**Comment by Jasagredo** [comment]
I think this is now correct and won't produce collisions with previous packages. Would you confirm @michaelpj please? I don't want to click merge and create another conflict again :smile:

**Comment by michaelpj** [comment]
Looks fine to me. Ultimately they're your packages, so up to you what you do with them :) we just don't want to mutate the package archive!

**Pull request merged**
