### PR TITLE
coot/typed protocols

### PR DESCRIPTION
**Pull request by coot**
- Added typed-protocols-0.1.0.1
- Added typed-protocols-cborg-0.1.0.1
- Added typed-protocols-examples-0.1.0.1

TODO:

- [ ] check that `typed-protocols-0.1.0.1` build.

### CODE REVIEW

**Comment by coot** [comment]
@michaelpj I build the foliage in `_repo` directory using branch of this PR with:
```bash
nix develop -c foliage build
```
now I am trying
```bash
nix build --override-input CHaP path:"$(pwd)/_repo"                                                     
warning: input '' has an override for a non-existent input 'CHaP'
warning: the flag '--override-input CHaP path:/home/coot/clients/iohk/cardano-haskell/cardano-haskell-packages/_repo' does not match any input
error: flake 'git+file:///home/coot/clients/iohk/cardano-haskell/cardano-haskell-packages' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

am I doing something wrong?

Well maybe I should start with what I want to do: check that `typed-protocols` build now, probably I need to modify the command to:
```bash
nix build .#typed-protocols --override-input CHaP path:"$(pwd)/_repo"
```

_I don't know what I am doing:tm:_

**Comment by michaelpj** [comment]
Ah yes, I meant to add some simpler "test it out" instructions. For now, something like this is a nice way to try things out. In a fresh directory:
```
-- Custom repository for cardano haskell packages, see CONTRIBUTING for more
repository cardano-haskell-packages
  url: https://input-output-hk.github.io/cardano-haskell-packages
  secure: True
  root-keys:
    3e0cce471cf09815f930210f7827266fd09045445d65923e6d0238a6cd15126f
    443abb7fb497a134c343faf52f0b659bd7999bc06b7f63fa76dc99d631f9bea1
    a86a1f6ce86c449c46666bda44268677abf29b5b2d2eb5ec7af903ec2f117a82
    bcec67e8e99cabfa7764d75ad9b158d72bfacf70ca1d0ec8bc6b4406d1bf8413
    c00aae8461a256275598500ea0e187588c35a5d5d7454fb57eac18d9edb86a56
    d4a35cd3121aa00d18544bb0ac01c3e1691d618f462c46129271bccf39f7e8ee

-- adjust as needed
index-state: 2022-07-01T00:00:00Z
index-state: cardano-haskell-packages 2022-10-17T00:00:00Z

-- add all the packages you like
extra-packages:
  cardano-prelude
```
```
$ cabal build cardano-prelude --constraint "cardano-prelude==0.1.0.0"
```

**Comment by michaelpj** [comment]
I added a PR describing the process in more detail. I also checked this myself and everything built fine. The only thing that would be nice is some lower bounds on `io-classes`, since the new version won't build with the old `io-classes`. But you already tagged `0.1.0.1` so you'd probably want to do another release for that. We can do it as a revision in the mean time.

**Comment by coot** [comment]
`typed-protocols-examples` have no bounds on `io-classes` or `io-sim`; and vice versa `io-sim:test` does not set any bounds on `typed-protocols-examples` :upside_down_face:.

**Comment by coot** [comment]
You'll probably right, e.g. like `>= 0.1.0.0`, but that's anyway always true for `CHaP` :shrug:.

**Pull request merged**
