### PR TITLE
Update hackage.nix

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by Jasagredo** [comment]
What is the difference between consensus 0.3.0.0 and the revision you publish in this PR?

**Comment by michaelpj** [comment]
I'll tell you once I'm done :) basically I'm adding bounds on `unix-bytestring` like @coot did in https://github.com/input-output-hk/cardano-haskell-packages/pull/177

**Comment by michaelpj** [comment]
Also I said in the commit message. Really we need https://github.com/andreabedini/foliage/issues/42 to make this sort of thing actually reviewable!

**Comment by michaelpj** [comment]
I had to revise all the ouroboros-consensus package versions in the end, cabal is very keen to pick a newer `unix-bytestring` :laughing:

**Comment by michaelpj** [comment]
cc @input-output-hk/ouroboros-consensus 

Hard to review I know.

**Comment by michaelpj** [comment]
(In case it wasn't clear, this should be ready to go)

**Pull request merged**
