### PR TITLE
scripts/add-revision.sh: Improve error reporting

### PR DESCRIPTION
**Pull request by erikd**
I looked into actually retrieving the needed cabal file but that seems a little too fragile, so report the error, create the required  directory and suggest copying the needed cabal file.

### CODE REVIEW

**Review by angerman — APPROVED** [review]
LGTM, however, it's not clear to me yet how to end up in this situation? Why wouldn't the current cabal file exist?

**Comment by erikd** [comment]
> LGTM, however, it's not clear to me yet how to end up in this situation? Why wouldn't the current cabal file exist?

Its the cabal file for the package we are modifying. That directory is populated by (as I understand it) a Nix program called `folliage`. If you don't have Nix, then you will not have this file,

**Comment by michaelpj** [comment]
I guess this is fine. You can also just download the repository and pass that if you don't want to use foliage.

**Comment by michaelpj** [comment]
@erikd `foliage` is a Haskell program. You can go `cabal build` https://github.com/andreabedini/foliage if you don't want to use Nix.

**Pull request merged**
