### PR TITLE
Added cardano-strict-containers-0.1.1.0

### PR DESCRIPTION
**Pull request by lehins**
From https://github.com/input-output-hk/cardano-base at 319b70ae75243620594dca056bd27b7f447b4cde

### CODE REVIEW

**Comment by michaelpj** [comment]
It would be better not to do this before the PR in the repo is merged.

**Comment by michaelpj** [comment]
Otherwise there's a risk that the commit could get lost.

**Comment by lehins** [comment]
@michaelpj Yeah, I know this. I did this release as a demo to our team on a video call. There was no time to wait for CI, so I did take the risk, however I did mention it during a call  that the PR with version bump must be merged before the release to CHaP.

**Comment by michaelpj** [comment]
Okay, no worries!

**Pull request merged**
