### PR TITLE
Add marlowe-plutus-0.1.0.0

### PR DESCRIPTION
**Pull request by jhbertra**
- [x] Adds marlowe-plutus package
- [x] Adds marlowe-runtime as a smoke test package.
      - This was breaking frequently because of improperly constrained dependency versions in upstream packages, as such it is an excellent smoke test to detect breakages.

### CODE REVIEW

**Comment by michaelpj** [comment]
> Adds marlowe-runtime as a smoke test package

:+1:

**Comment by jhbertra** [comment]
Removed marlowe-runtime smoke test because the build was exceeding 4 hours.

**Comment by michaelpj** [comment]
That's not necessarily a problem: it should all get cached :thinking:

**Comment by michaelpj** [comment]
Added in https://github.com/input-output-hk/cardano-haskell-packages/pull/500

**Pull request merged**
