### PR TITLE
Marlowe Runtime 0.0.2

### PR DESCRIPTION
**Pull request by jhbertra**

### CODE REVIEW

**Comment by shlevy** [comment]
@input-output-hk/cardano-haskell-packages-trustees Note the changes to `builder.nix`

**Review by andreabedini — APPROVED** [review]
Could you also open an issue that references the workaround 🙏

**Comment by shlevy** [comment]
Latest commit to test https://github.com/kazu-yamamoto/crypton/pull/7

**Comment by shlevy** [comment]
@andreabedini Created #352

**Pull request merged**
